@host=https://localhost:7229

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Ivan",
    "lastName": "Janjic",
    "email": "amichai@mantinband.com",
    "password": "Amiko1232!"
}