@host=http://localhost:5179
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTY5NGYxNS1lYTdjLTRmMTctODIyNi02MGJhMmJhYmNlNjYiLCJnaXZlbl9uYW1lIjoiQW1pa28iLCJmYW1pbHlfbmFtZSI6IkRhcmsiLCJqdGkiOiI2NzY5OWZlMS1kOWJkLTQ2YTctYTI3Ni05MGJmMTJhZjJhZDQiLCJleHAiOjE2Njg4NjQwNDAsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.dTf7dwUz2AN8C-n-qnaD-M7T80jbE3RL5ol0CqbQTS4
@hostId=asdf

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "",
    "description": "",
    "sections": [
    ]
}