@host=https://localhost:7229

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJzdWIiOiJhNDg0ZTdmYy1kZDAzLTQwZDYtYmUwOC0yNjk3ODI2NTNhOGYiLCJnaXZlbl9uYW1lIjoiQW1pa28iLCJmYW1pbHlfbmFtZSI6IkRhcmsiLCJqdGkiOiI4OTkxMTYxZC0zZjZkLTQyNDEtOWZmMS05OWYzZGVlZWMxZDAiLCJleHAiOjE2NjExODY1NTQsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.4LqTWbdjKGWAkS60a7OAgU4CeLgjHjl5euEK3jnyajo