@host=http://localhost:5179

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJzdWIiOiI0YWJmMTliYi1kZWVjLTRhYzktODkyZi00MGJiN2JhN2Q2ZjciLCJnaXZlbl9uYW1lIjoiSXZhbiIsImZhbWlseV9uYW1lIjoiSmFuamljIiwianRpIjoiYTFhZTk2NzUtYjA3NS00NGZiLTgwMTgtZWMzNDEwOGNkYzg4IiwiZXhwIjoxNjkwOTEwODU2LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.Y6-Z4UUBWgGblwI-VsOhugao2j_ktjbp5ARcSae20QQ
